# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358108fe8baa52cf5f66f4407b4ff822627d23548bd9284c557c615749d586d37a6f23113784c39aa5a97d2a3b0412ecb7b861ad5baea2bb2da09eabf87f05eb

test:
  secret_key_base: 39b7921de7b67bfe208062e46f1179733c52444eec906398ddc31af4e5652283164f49c31200b5e9bd474404caf04ebde1260d70b156822972cc73fb96c3ec3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
